version: "2"

linters:
  enable:
    - decorder

  settings:
    decorder:
      dec-order:
        - const
        - type
        - var
        - func
      disable-dec-order-check: false
      disable-dec-num-check: true
      ignore-underscore-vars: true
