version: "3"

tasks:
  default:
    cmds:
      - task: check

  setup:
    desc: Interactive setup - installs tools and prompts for API keys
    cmds:
      - go run . setup

  run:
    cmds:
      - go run . {{.CLI_ARGS}}

  build:
    cmds:
      - go build -o bin/craftstory .

  test:
    cmds:
      - go test -race -cover ./...

  lint:
    cmds:
      - golangci-lint run

  fmt:
    cmds:
      - go fmt ./...
      - go mod tidy

  check:
    cmds:
      - go fmt ./...
      - go mod tidy
      - golangci-lint run
      - go test -race ./...
