version: "3"

tasks:
  default:
    cmds:
      - task: check

  run:
    cmds:
      - go run ./cmd/craftstory {{.CLI_ARGS}}

  build:
    cmds:
      - go build -o bin/craftstory ./cmd/craftstory

  test:
    cmds:
      - go test -race -cover ./...

  lint:
    cmds:
      - golangci-lint run

  fmt:
    cmds:
      - go fmt ./...
      - go mod tidy

  check:
    cmds:
      - go fmt ./...
      - go mod tidy
      - golangci-lint run
      - go test -race ./...
