version: "3"

tasks:
  run:
    cmds:
      - go run ./cmd/craftstory {{.CLI_ARGS}}

  build:
    cmds:
      - go build -o bin/craftstory ./cmd/craftstory

  test:
    cmds:
      - go test -race -cover ./...

  test-integration:
    cmds:
      - go test -race -tags=integration ./...

  lint:
    cmds:
      - golangci-lint run

  check:
    cmds:
      - golangci-lint run
      - go test -race ./...

  xtts:
    desc: Start XTTS server
    cmds:
      - docker compose up -d

  xtts:down:
    desc: Stop XTTS server
    cmds:
      - docker compose down

  xtts:logs:
    desc: Show XTTS server logs
    cmds:
      - docker compose logs -f

  add-voice:
    desc: Add voice sample from YouTube for a character
    cmds:
      - ./scripts/add-voice.sh {{.CLI_ARGS}}
