version: "3"

tasks:
  run:
    cmds:
      - go run ./cmd/craftstory generate {{.CLI_ARGS}}

  test:
    cmds:
      - go test ./...

  lint:
    cmds:
      - golangci-lint run

  check:
    cmds:
      - golangci-lint run
      - go test ./...

  docker-run:
    cmds:
      - docker build -t craftstory .
      - docker run --env-file .env craftstory generate {{.CLI_ARGS}}

  docker-down:
    cmds:
      - docker rm -f craftstory 2>/dev/null || true
