version: "3"

tasks:
  run:
    cmds:
      - go run ./cmd/craftstory {{.CLI_ARGS}}

  build:
    cmds:
      - go build -o bin/craftstory ./cmd/craftstory

  test:
    cmds:
      - go test -race -cover ./...

  lint:
    cmds:
      - golangci-lint run

  check:
    cmds:
      - golangci-lint run
      - go test -race ./...
